title: Nội Thất Chin Huei - KTS Cường Nguyễn
description: Thiết kế và thi công nội thất nhựa Đài Loan Chin Huei 2.0 Plus cao cấp.
url: "https://ktscuongnguyen.github.io"
baseurl: ""

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
defaults:
  - scope:
      path: "du-an"
    values:
      layout: "post"
